services:
  server:
    build: .
    ports:
      - 80:8080
    environment:
      DB_USER: postgres
      DB_PWD: IWR698oOsjZDX1RypOcq
      DB_HOST: bia-db.cupu2eku4zq6.us-east-1.rds.amazonaws.com
      DB_PORT: 5432
